name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes

jobs:
  keep_alive_job:
    runs-on: ubuntu-latest

    steps:
      - name: Send a request to keep the app awake
        run: |
          curl -I https://your-streamlit-app-url.com
