[client]
showSidebarNavigation = false
showErrorDetails = false
toolbarMode = "viewer"

[theme]
base="light"
primaryColor="#8b0000"

[server]
maxUploadSize = 100
runOnSave = true
headless = true

[ui]
hideTopBar = true